name: Tests E2E

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop
      - 'feature/**'
    tags:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  LANG: "pt_BR.UTF-8"
  LANGUAGE: "pt_BR:pt"
  LC_ALL: "pt_BR.UTF-8"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone America/Sao_Paulo
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setup LANG=pt_BR.UTF-8
        run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
          date

      - name: Configure git repository
        uses: actions/checkout@v4

      - name: Configuring Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Configuring WebDriver for Chrome
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '129.0.6668.58'

      - name: Run Test
          run: |
            export PIPELINE=github_actions
            mvn -q test || true

      - name: Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-test
          path: 'target/report-builder'

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs:
      - test
    environment:
      name: github-pages
      url: https://marilliadantas.github.io/adopet-selenium

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: report-test

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy files no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4